# Generated by Django 5.2.4 on 2026-07-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('prediction_made', 'Prediction Made'), ('report_uploaded', 'Report Uploaded'), ('report_analyzed', 'Report Analyzed'), ('recommendation_generated', 'Recommendation Generated'), ('review_decision', 'Review Decision'), ('conflict_detected', 'Conflict Detected'), ('conflict_resolved', 'Conflict Resolved'), ('export_generated', 'Export Generated'), ('feedback_received', 'Feedback Received'), ('emergency_detected', 'Emergency Detected'), ('safety_alert', 'Safety Alert'), ('medication_change', 'Medication Change')], db_index=True, max_length=64)),
                ('event_detail', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='system', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('prediction_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('feedback_type', models.CharField(choices=[('correct', 'Correct'), ('partially_correct', 'Partially Correct'), ('incorrect', 'Incorrect'), ('missing_information', 'Missing Information'), ('hallucination', 'Hallucination')], max_length=32)),
                ('original_output', models.TextField(blank=True)),
                ('corrected_output', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_synthetic_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(db_index=True, max_length=64)),
                ('recommendation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ai_summary', models.TextField(blank=True)),
                ('clinician_decision', models.CharField(choices=[('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], max_length=16)),
                ('clinician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
