# Generated by Django 5.2.4 on 2026-07-27 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('standardised_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('original_value', models.CharField(max_length=255)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=64)),
                ('normalised_unit', models.CharField(blank=True, max_length=64)),
                ('reference_range_low', models.FloatField(blank=True, null=True)),
                ('reference_range_high', models.FloatField(blank=True, null=True)),
                ('reference_range_text', models.CharField(blank=True, max_length=255)),
                ('abnormality_status', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('critically_high', 'Critically High'), ('critically_low', 'Critically Low'), ('unable_to_assess', 'Unable to Assess'), ('not_tested', 'Not Tested')], default='unable_to_assess', max_length=32)),
                ('collection_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('corrected', 'Corrected'), ('entered_in_error', 'Entered in Error')], default='unverified', max_length=32)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='reports.medicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('medication_mismatch', 'Medication Mismatch'), ('value_discrepancy', 'Value Discrepancy'), ('report_summary_vs_data', 'Report Summary vs Data'), ('condition_misreported', 'Condition Misreported'), ('demographic_mismatch', 'Demographic Mismatch'), ('temporal_conflict', 'Temporal Conflict'), ('prediction_vs_input', 'Prediction vs Input'), ('ai_vs_structured', 'AI vs Structured Data'), ('timeline_vs_record', 'Timeline vs Record'), ('duplicate_observation', 'Duplicate Observation'), ('other', 'Other')], max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('first_source_label', models.CharField(max_length=255)),
                ('first_source_detail', models.TextField(blank=True)),
                ('first_source_record_id', models.CharField(blank=True, max_length=64)),
                ('second_source_label', models.CharField(max_length=255)),
                ('second_source_detail', models.TextField(blank=True)),
                ('second_source_record_id', models.CharField(blank=True, max_length=64)),
                ('explanation', models.TextField(blank=True)),
                ('detection_method', models.CharField(default='rule_based', max_length=64)),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('first_source_confirmed', 'First Source Confirmed'), ('second_source_confirmed', 'Second Source Confirmed'), ('both_uncertain', 'Both Uncertain'), ('correction_added', 'Correction Added'), ('dismissed', 'Dismissed')], db_index=True, default='unresolved', max_length=32)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(blank=True, max_length=64)),
                ('report_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('performing_lab', models.CharField(blank=True, max_length=255)),
                ('ordering_clinician', models.CharField(blank=True, max_length=255)),
                ('clinical_notes', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_records', to='reports.medicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('age_min', models.FloatField(blank=True, null=True)),
                ('age_max', models.FloatField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='clinical.clinicalobservation')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(db_index=True, max_length=255)),
                ('absolute_change', models.FloatField(blank=True, null=True)),
                ('percentage_change', models.FloatField(blank=True, null=True)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('fluctuating', 'Fluctuating'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('is_persistent_abnormality', models.BooleanField(default=False)),
                ('is_sudden_change', models.BooleanField(default=False)),
                ('is_missing_follow_up', models.BooleanField(default=False)),
                ('is_conflicting', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('earlier_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earlier_trends', to='clinical.clinicalobservation')),
                ('later_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='later_trends', to='clinical.clinicalobservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('routine', 'Routine'), ('review_soon', 'Review Soon'), ('review_today', 'Review Today'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=32)),
                ('snapshot_data', models.JSONField(default=dict)),
                ('critical_findings', models.JSONField(blank=True, default=list)),
                ('recent_changes', models.JSONField(blank=True, default=list)),
                ('active_risks', models.JSONField(blank=True, default=list)),
                ('supporting_evidence', models.JSONField(blank=True, default=list)),
                ('contradictory_evidence', models.JSONField(blank=True, default=list)),
                ('medication_concerns', models.JSONField(blank=True, default=list)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('uncertainty_notes', models.JSONField(blank=True, default=list)),
                ('suggested_next_steps', models.JSONField(blank=True, default=list)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_state_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalobservation',
            index=models.Index(fields=['user', 'standardised_name'], name='clinical_cl_user_id_349303_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalobservation',
            index=models.Index(fields=['user', 'collection_date'], name='clinical_cl_user_id_6ed650_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconflict',
            index=models.Index(fields=['user', 'resolution_status'], name='clinical_da_user_id_694b10_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconflict',
            index=models.Index(fields=['conflict_type'], name='clinical_da_conflic_a73006_idx'),
        ),
        migrations.AddIndex(
            model_name='observationtrend',
            index=models.Index(fields=['user', 'test_name'], name='clinical_ob_user_id_e52784_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatesnapshot',
            index=models.Index(fields=['user', '-created_at'], name='clinical_pa_user_id_24f0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='patientstatesnapshot',
            index=models.Index(fields=['user', 'is_current'], name='clinical_pa_user_id_bee0b5_idx'),
        ),
    ]
