# Generated by Django 5.2.4 on 2026-07-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rxnorm_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('drug_class', models.CharField(blank=True, max_length=255)),
                ('common_side_effects', models.JSONField(blank=True, default=list)),
                ('serious_side_effects', models.JSONField(blank=True, default=list)),
                ('contraindications', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(db_index=True, max_length=255)),
                ('rxnorm_code', models.CharField(blank=True, max_length=64)),
                ('reaction_type', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['allergen'],
            },
        ),
        migrations.CreateModel(
            name='MedicationExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_method', models.CharField(default='llm', max_length=64)),
                ('medications_found', models.JSONField(blank=True, default=list)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('is_synthetic_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_extractions', to='reports.medicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=128)),
                ('frequency', models.CharField(blank=True, max_length=128)),
                ('route', models.CharField(blank=True, max_length=64)),
                ('prescribed_for', models.CharField(blank=True, max_length=255)),
                ('prescriber', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold'), ('unknown', 'Unknown')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='medication.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drug_interaction', 'Drug Interaction'), ('allergy_conflict', 'Allergy Conflict'), ('duplicate_therapy', 'Duplicate Therapy'), ('contraindication', 'Contraindication'), ('overdosage_risk', 'Overdosage Risk'), ('missing_info', 'Missing Information')], max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='unresolved', max_length=16)),
                ('resolution_notes', models.TextField(blank=True)),
                ('is_synthetic_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_medication_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_safety_alerts', to=settings.AUTH_USER_MODEL)),
                ('medications_involved', models.ManyToManyField(related_name='safety_alerts', to='medication.patientmedication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('dose_taken', 'Dose Taken'), ('dose_skipped', 'Dose Skipped'), ('dose_late', 'Dose Late'), ('side_effect', 'Side Effect'), ('dose_changed', 'Dose Changed'), ('medication_stopped', 'Medication Stopped'), ('medication_started', 'Medication Started'), ('adverse_reaction', 'Adverse Reaction')], max_length=32)),
                ('event_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_events', to=settings.AUTH_USER_MODEL)),
                ('patient_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='medication.patientmedication')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
